### ISSUE TITLE
can't compile example-wrapper on rpi4 buster of 0.11.0, linker error 'ofxOMXPhotoGrabber.o: undefined reference to symbol 'eglCreateImageKHR''

### ISSUE THREAD

**Issue by robin-price** [jvcleave/ofxOMXCamera#10]
All other examples compile.

`Linking bin/example-wrapper for linuxarmv6l
g++ -o bin/example-wrapper  obj/linuxarmv6l/Release/src/main.o obj/linuxarmv6l/Release/src/ofApp.o  ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/OMXCameraController.o ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/VideoEngine.o ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/RPiVideoGrabber.o ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/PhotoEngine.o ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/VideoRecorder.o ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/ofxOMXPhotoGrabber.o ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/ofxOMXVideoGrabber.o  ../../../libs/openFrameworksCompiled/lib/linuxarmv6l/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -pthread -latomic -L/opt/vc/lib ../../../libs/kiss/lib/linuxarmv6l/libkiss.a ../../../libs/tess2/lib/linuxarmv6l/libtess2.a   -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lcurl -lglfw -lrtaudio -lasound -lpulse-simple -lpulse -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lmpg123 -lGLEW -lGLU -lGL -lfreeimage -lboost_filesystem -lboost_system -lpugixml -luriparser -lXinerama -lglfw -lGLESv2 -lGLESv1_CM -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpcre -lrt -lX11 -ldl
/usr/bin/ld: ../../../addons/obj/linuxarmv6l/Release/ofxOMXCamera/src/ofxOMXPhotoGrabber.o: undefined reference to symbol 'eglCreateImageKHR'
/usr/bin/ld: //opt/vc/lib/libbrcmEGL.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:405: bin/example-wrapper] Error 1
make[1]: Leaving directory '/home/pi/of_v20191209/addons/ofxOMXCamera/example-wrapper'
make: *** [../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2`

**Comment by jvcleave** [comment]
Good to see some stuff compiles! I don't currently have an RPI4 and I know stuff changed with the drivers

Looks like some adjustments need to be made - this thread may provide clues

https://www.raspberrypi.org/forums/viewtopic.php?f=68&t=243892&p=1500721&hilit=eglCreateImageKHR#p1500721

**Comment by robin-price** [comment]
Thanks, I think I may have spoken too soon about other things building. I'd ran build all examples and it seems to run in reverse order, I thought it had built the others and failed at example-wrapper.

I've successfully ran 6by9's https://github.com/6by9/drm_mmal/tree/x11_export meson ninja build and the example still doesn't compile but I'm not entirely sure what if anything running it does. I can't seem to run the mmal demo or see a library or anything to link off plop out at the end. Hmmmm.

**Comment by ofTheo** [comment]
Here is some more info - looks like you need to help the newer mesa drivers with calls like: eglCreateImageKHR

https://github.com/intel/libyami/pull/252

**Comment by robin-price** [comment]
Presumably I need to adapt DisplayController.h and replace eglCreateImageKHR with a call to createImage which I then define somewhere using the sample code in their fix?

**Comment by zixzixzix** [comment]
the same problem rpi4

**Comment by jvcleave** [comment]
Finally got an RPi4 but things aren't looking good. It seems like the OpenMax egl_render component is essentially gone with the new device. 

This is what allowed the direct rendering to textures to happen. I'm thinking even if I got the `eglCreateImageKHR` the OpenMax component would fail.

Seeing similar stuff like this
https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/hello_pi/hello_videocube/triangle.c#L476

**Comment by jvcleave** [comment]
@crx091081gb I think the way forward may be the drm_mmal path. I got the example code working (just did Console mode so far). This issue may help (there are different branches for X11, Console is the master)

https://github.com/6by9/drm_mmal/issues/4

**Comment by jvcleave** [comment]
pushing all RPI4 related stuff to 
https://github.com/jvcleave/ofxOMXCamera/issues/11
