### ISSUE TITLE
no whitebalance

### ISSUE THREAD

**Issue by MartinHN** [jvcleave/ofxOMXCamera#6]
Hi,
when setting whitebalance to "Off" the image seems to stay super greenish, with little to no change while playing around with the GainR and GainB values (0.0 - 1.0) . 
is it the expected behaviour?

I can provide sample codes and or snapshot if needed

Thanks

**Comment by jvcleave** [comment]
Here is some output differences I see. It may need some custom configuration with `whiteBalanceGainsConfig` to be useful. 

http://www.jvcref.com/files/PI/documentation/ilcomponents/prop.html#OMX_IndexConfigCustomAwbGains


Auto:
![2019-01-05-17-32-49-628_q100](https://user-images.githubusercontent.com/150037/50727245-3ccb7500-10e6-11e9-87c6-67802a6fd1ed.jpg)

with various gains added:

![2019-01-05-17-33-22-557_q100](https://user-images.githubusercontent.com/150037/50727242-3c32de80-10e6-11e9-965d-20439a389791.jpg)
![2019-01-05-17-33-10-350_q100](https://user-images.githubusercontent.com/150037/50727243-3ccb7500-10e6-11e9-9980-5d1dd00792d3.jpg)
![2019-01-05-17-33-01-769_q100](https://user-images.githubusercontent.com/150037/50727244-3ccb7500-10e6-11e9-8602-64a557751bfb.jpg)

**Comment by jvcleave** [comment]
This is the struct for that - looks like that is all that is available
```
typedef struct OMX_CONFIG_CUSTOMAWBGAINSTYPE {
   OMX_U32 nSize;                      /**< size of the structure in bytes, including
                                            configuration data */
   OMX_VERSIONTYPE nVersion;           /**< OMX specification version information */
   OMX_U32 xGainR;                     /**< Red gain - 16p16 */
   OMX_U32 xGainB;                     /**< Blue gain - 16p16 */
} OMX_CONFIG_CUSTOMAWBGAINSTYPE;
```

what's also likely is that it may not take a float but need to be an int value formatted like this

https://github.com/gagle/raspberrypi-omxcam/blob/0459f77c39775fce0ef9ddb7028fe2243b211729/src/camera.c#L456

**Comment by MartinHN** [comment]
thanks for the links!
it seems indeed that we can't manage to aproximate a white balance config only with the gainR and gainB,  what I ended to do is to add a OMX_ImageFilterColourBalance with customs RGB parameters to approximate a white balance.

thanks again
